local module = require(script.Parent:FindFirstChild(".pesde"):FindFirstChild("littensy_ripple@0.10.2"):FindFirstChild("ripple"))
export type Animatable  = module.Animatable 
export type AnimatableType  = module.AnimatableType 
export type AnimatablePrimitive  = module.AnimatablePrimitive 
export type Easing  = module.Easing 
export type Motion<T = any> = module.Motion<T >
export type MotionOptions<T = any> = module.MotionOptions<T >
export type Spring<T = any> = module.Spring<T >
export type SpringOptions<T = any> = module.SpringOptions<T >
export type Tween<T = any> = module.Tween<T >
export type TweenOptions<T = any> = module.TweenOptions<T >
return module